force-app/main/default/objects/Case/fields/Product_Sku__c.field-meta.xml
<CustomField>
    <fullName>Product_Sku__c</fullName>
    <label>Product Sku</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/QOH__c.field-meta.xml
<CustomField>
    <fullName>QOH__c</fullName>
    <description>Quantity On Hand</description>
    <formula>rstk__Product_icitem__r.FMG_On_Hand_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Quantity On Hand</inlineHelpText>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseProductRelatedListComponentTest.cls
@isTest
public class CaseProductRelatedListComponentTest {
    @isTest
    public static void testGetOrderSummaries() {
        // Test data setup
        Case testCase = new Case();
        testCase.Product_Sku__c = 'TestSKU';
        insert testCase;

        Product2 testProduct = new Product2();
        testProduct.StockKeepingUnit = 'TestSKU';
        testProduct.Name='Test Product';
        testProduct.IsActive = false;
        //testProduct.QOH__c = 10;
        insert testProduct;

        // Test the getOrderSummaries method
        Test.startTest();
        List<Product2> orderSummaries = CaseProductRelatedListComponent.getOrderSummaries(testCase.Id);
        Test.stopTest();

        // Assertion
        System.assertEquals(1, orderSummaries.size());
        Product2 orderSummary = orderSummaries[0];
        System.assertEquals('TestSKU', orderSummary.StockKeepingUnit);
    }
}