force-app/main/default/objects/Case/fields/Product_Sku__c.field-meta.xml
<CustomField>
    <fullName>Product_Sku__c</fullName>
    <label>Product Sku</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/QOH__c.field-meta.xml
<CustomField>
    <fullName>QOH__c</fullName>
    <description>Quantity On Hand</description>
    <formula>rstk__Product_icitem__r.FMG_On_Hand_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Quantity On Hand</inlineHelpText>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseProductRelatedListComponent.cls
public class CaseProductRelatedListComponent {
    @AuraEnabled
    public static List<Product2> getOrderSummaries(string caseId) {
        String accId='';
        string productsku='';
        List<Product2> orderSummaries;
        If(caseId != NULL && !string.isBlank(caseId)) {
            productsku=[SELECT Product_Sku__c FROM Case WHERE Id = :caseId].Product_Sku__c;
        }
        System.debug('ProductSku:'+productsku);
        If(productsku != NULL && !string.isBlank(productsku)) {
            System.debug('ProductSku:'+productsku);
          orderSummaries = [SELECT Id,Name, StockKeepingUnit,QOH__c FROM Product2 WHERE StockKeepingUnit= :productsku];  
            System.debug('OrderSummary1: '+orderSummaries);
        }   
        System.debug('OrderSummary1: '+orderSummaries);
        return orderSummaries;
    }
    /*
    @auraEnabled
    public static string returnAccountId(string caseId){
        
        string accId='';
        List<OrderSummary> orderSummaries;
        
        If(caseId != NULL && !string.isBlank(caseId)) {
            accId = [SELECT AccountId FROM Case WHERE Id = :caseId].AccountId;
            system.debug('accId :'+accId);
        }
        
        return accId;
    }*/
}