force-app/main/default/objects/BraintreeCaptureError__c/BraintreeCaptureError__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BraintreeCaptureError</label>
</CustomObject>

force-app/main/default/objects/BraintreeCaptureError__c/fields/Delay_For_Payment_Capture_Check__c.field-meta.xml
<CustomField>
    <fullName>Delay_For_Payment_Capture_Check__c</fullName>
    <label>Delay For Payment Capture Check</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BraintreeCaptureErrorClass.cls
Public class BraintreeCaptureErrorClass {
    @InvocableMethod(label='Capture Braintree Errors')
    public Static void braintreeCaptureError(createListInputs[] inputLists) {
    Map<Id,Id> FulfillmentandBackgroundIdsMap = new Map<Id,Id>();
        for(Integer i = 0; i < inputLists[0].BGIds.size(); i++) {
            FulfillmentandBackgroundIdsMap.put(inputLists[0].BGIds.get(i), inputLists[0].FOIds.get(i));
            System.debug('FulfillmentIDs'+ inputLists[0].FOIds.get(i));
            System.debug('BackgroundoperationIDs'+inputLists[0].BGIds.get(i));
        }
        if(FulfillmentandBackgroundIdsMap.size()>0) {

            System.debug('FulfillmentandBackgroundIdsMap: '+FulfillmentandBackgroundIdsMap);
            BraintreeCaptureError__c DelayTime = BraintreeCaptureError__c.getValues('Schedule Time');
            system.debug(DelayTime.Delay_For_Payment_Capture_Check__c);
            Integer DelayForPaymentCapture = (Integer)DelayTime.Delay_For_Payment_Capture_Check__c;

            Datetime currentTime = Datetime.now();
            Datetime scheduledTime = currentTime.addMinutes(DelayForPaymentCapture);
            String scheduleName = 'Schedule BraintreeCaptureErrors (FOId: '+inputLists[0].FOIds[0]+')';
            String cronExpression = '0 '+scheduledTime.minute()+' '+scheduledTime.hour()+' '+scheduledTime.day()+' '+scheduledTime.month()+' ? '+ scheduledTime.year();
            system.debug('cronExpression: '+cronExpression);
            system.schedule(scheduleName, cronExpression, new Schedule_BraintreeCaptureErrors(FulfillmentandBackgroundIdsMap));
        }
    }
    
    public class createListInputs {
        @InvocableVariable(label='Fulfillment Order Id' required=true)
        public Id[] FOIds;
        
        @InvocableVariable(label='Background Operation Id' required= true)
        public Id[] BGIds;
    }
}