force-app/main/default/objects/OCI_Job__mdt/OCI_Job__mdt.object-meta.xml
<CustomObject>
    <label>OCI Job</label>
    <pluralLabel>OCI Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/OCI_Job__mdt/fields/End_Count__c.field-meta.xml
<CustomField>
    <fullName>End_Count__c</fullName>
    <label>End Count</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Job__mdt/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Job__mdt/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OCI_Job__mdt/fields/Start_Count__c.field-meta.xml
<CustomField>
    <fullName>Start_Count__c</fullName>
    <label>Start Count</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Schedule_OciApiCallouts.cls
global class Schedule_OciApiCallouts Implements Schedulable,Database.AllowsCallouts{
    global void execute (SchedulableContext sc){
        
        List<OCI_Job__mdt> metadataRecords = [SELECT Id,MasterLabel, Start_Count__c,End_Count__c,Hours__c,Minutes__c FROM OCI_Job__mdt ORDER BY MasterLabel ASC];
        System.debug('metadataRecords--->'+metadataRecords);
        for (OCI_Job__mdt prodCount : metadataRecords) {
            System.debug('OCI_Job__mdt inside for--->'+ prodCount);
            String jobName = 'Schedule OCI Job';
            System.debug('jobName--->'+jobName);
            // Construct the cron expression based on offsetTime
            String cronExpression = '0 ' + Integer.valueOf(prodCount.Minutes__c) + ' ' + Integer.valueOf(prodCount.Hours__c) + ' * * ?';
            System.debug('cronExpression'+cronExpression);
            if(!Test.isRunningTest()){
	            System.schedule(prodCount.MasterLabel, cronExpression, new ScheduleBatchDailyOCI(Integer.valueOf(prodCount.Start_Count__c),Integer.valueOf(prodCount.End_Count__c)));
            }
            else{
               System.schedule('IsRunningTest'+ prodCount.MasterLabel, cronExpression, new ScheduleBatchDailyOCI(Integer.valueOf(prodCount.Start_Count__c),Integer.valueOf(prodCount.End_Count__c)));
               
            }
            
        }
        
    }
   
    
    
}