force-app/main/default/objects/CDP_Configuration_Setting__mdt/CDP_Configuration_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration page for CDP</description>
    <label>CDP Configuration Setting</label>
    <pluralLabel>CDP Configuration Setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/CDP_Configuration_Setting__mdt/fields/DaysAgo__c.field-meta.xml
<CustomField>
    <fullName>DaysAgo__c</fullName>
    <label>DaysAgo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleBatch_CDP.cls
global class ScheduleBatch_CDP implements Schedulable {
    global void execute(SchedulableContext sc) {
        // Start the batch job
        CDP_Configuration_Setting__mdt getCDPConfig = [SELECT Id,MasterLabel, DaysAgo__c from CDP_Configuration_Setting__mdt where MasterLabel = 'CDP Config' limit 1];

        UpdatePlatinumAttributesFromCDPBatch cdpbatch = new UpdatePlatinumAttributesFromCDPBatch(integer.valueof(getCDPConfig.DaysAgo__c));
        database.executeBatch(cdpbatch, 20);
    }
}