force-app/main/default/objects/FMG_OCAPI_Setting__mdt/FMG_OCAPI_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Collection of OCAPI Settings like, CLIENT_ID, CLIENT_SECRET, AUTH_URL etc.,</description>
    <label>FMG_OCAPI_Setting</label>
    <pluralLabel>FMG_OCAPI_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FMG_OCAPI_Setting__mdt/fields/Product_Size__c.field-meta.xml
<CustomField>
    <fullName>Product_Size__c</fullName>
    <defaultValue>&apos;75&apos;</defaultValue>
    <label>Product Size</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getSFDCProducttoSFCC.cls
public class getSFDCProducttoSFCC {
    @InvocableMethod(label='Update Products in SFCC' description='This method is used to Upsert Products in SFCC' category='Product')
    Public static void getProductdetails(List<Product2> productList){
        
        List<id> productIds = new List<id>();
        Integer count=0;
        Integer batchsize = 75; 
        
        FMG_OCAPI_Setting__mdt FMGOCAPISettings = FMG_OCAPI_Setting__mdt.getinstance('FMG_OCAPI');
        if(FMGOCAPISettings.Product_Size__c != Null){
            batchsize = Integer.ValueOf(FMGOCAPISettings.Product_Size__c);
        }
        
        for ( product2 prd : productList){
            productIds.add(prd.id);
            if ( count++ > batchsize){
                System.debug('Processing batch -- productList size: '+productIds.size());
                ProductOMSSFCC.generateAccessTokenMetod(productIds);
                count = 0; //reset count
                productIds.clear() ; // reset list
            }
        }
        System.debug('Processing last batch -- productList size: '+productIds.size());
        if (productIds.size() > 0) // any remaining items
            ProductOMSSFCC.generateAccessTokenMetod(productIds);
    }
}