force-app/main/default/objects/Account/fields/Life_Time_Order_Count__c.field-meta.xml
<CustomField>
    <fullName>Life_Time_Order_Count__c</fullName>
    <label>Life Time Order Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Gift_Certificate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Gift_Certificate_Amount__c</fullName>
    <label>Total Gift Certificate Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Orders_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Orders_Amount__c</fullName>
    <label>Total Orders Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UpdateCustomerLifetimeAttributesBatch.cls
global class UpdateCustomerLifetimeAttributesBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'select id,Life_Time_Order_Count__c,Total_Gift_Certificate_Amount__c,Total_Orders_Amount__c from Account';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accountList) {
        updateCustomerLifetimeAttributesHandler.updateCustomerLifetimeAttributes(accountList);
    }
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
}