force-app/main/default/objects/Account/fields/Perf365Days__c.field-meta.xml
<CustomField>
    <fullName>Perf365Days__c</fullName>
    <label>365 Days $</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PerfCurrPeriodAmt__c.field-meta.xml
<CustomField>
    <fullName>PerfCurrPeriodAmt__c</fullName>
    <label>Period Plan $</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PerfPlanTotalAmt__c.field-meta.xml
<CustomField>
    <fullName>PerfPlanTotalAmt__c</fullName>
    <label>Platinum Total Program $</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PlatinumPriorPeriod__c.field-meta.xml
<CustomField>
    <fullName>PlatinumPriorPeriod__c</fullName>
    <label>Prior Yr Plan $</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdatePriorAndLyTyAmtBatch.cls
global class UpdatePriorAndLyTyAmtBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'select id,Perf365Days__c,PerfCurrPeriodAmt__c,PerfPlanTotalAmt__c,PlatinumPriorPeriod__c from Account';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accountList) {
     //   CustomerUpdateBatchhandler.updatePriorAndLyTyAmt(accountList);
    }
    
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
}