force-app/main/default/objects/Lead/fields/APT_Suite__c.field-meta.xml
<CustomField>
    <fullName>APT_Suite__c</fullName>
    <label>APT /Suite</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Catalog_Offer_Code_Sent__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Offer_Code_Sent__c</fullName>
    <label>Catalog Offer Code Sent</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Catalog_Status__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Status__c</fullName>
    <label>Catalog Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Inprocess</fullName>
            </value>
            <value>
                <fullName>Mailed</fullName>
            </value>
            <value>
                <fullName>Vendor Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CheckScheduleJobCompleted__c.field-meta.xml
<CustomField>
    <fullName>CheckScheduleJobCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CheckScheduleJobCompleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Estimated_In_Home_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_In_Home_Date__c</fullName>
    <label>Estimated In Home Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_BatchLeadConversion.cls
@isTest
public class Test_BatchLeadConversion {
    static testMethod void leadBatchTestMethod1(){
        Lead l = new Lead();
        l.FirstName='Test';
        l.LastName='Lead';
        l.Email='testlead@batch.com';
        l.leadsource='Catalog Request';
        l.CheckScheduleJobCompleted__c = false;
        l.Status = 'New';
        l.APT_Suite__c='123';
        insert l;
        
        l.Catalog_Offer_Code_Sent__c = 'TEST BATCH';
        l.Catalog_Status__c = 'Mailed';
        l.Estimated_In_Home_Date__c=  Date.newInstance(2024, 01, 3);
        update l;
        
        Test.startTest();
        BatchLeadConversion ba= new BatchLeadConversion();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
         
    }
    
    static testMethod void leadBatchTestMethod2(){
        Test.startTest();
        Account acc = new Account();
        acc.LastName = 'Test Account';
        acc.PersonEmail = 'testleadaccEx@batch.com';
        acc.BillingCity = 'Wilmington';
        insert acc;
        
        Lead l = new Lead();
        l.FirstName='Test';
        l.LastName='Lead';
        l.Email='testleadaccEx@batch.com';
        l.leadsource='Catalog Request';
        l.CheckScheduleJobCompleted__c = false;
        l.Status = 'New';
        l.APT_Suite__c='123';
        insert l;
        
        l.Catalog_Offer_Code_Sent__c = 'TEST BATCH';
        l.Catalog_Status__c = 'Mailed';
        l.Estimated_In_Home_Date__c=  Date.newInstance(2024, 01, 3);
        update l;
        
        
        BatchLeadConversion ba= new BatchLeadConversion();
        Id jobid= Database.executeBatch(ba,1);
        Test.stopTest();
        //list<task> tsList = [select id,WhatId,Subject from task where WhatId=:acc.id and type='Catalog Mailed'];
        //system.assertEquals(tsList[0].Subject, 'Catalog Mailed');
        //

    }
}